fen.input_2.clicked.connect(input2)
fen.input_3.clicked.connect(input3)
fen.input_4.clicked.connect(input4)
fen.input_5.clicked.connect(input5)
fen.input_6.clicked.connect(input6)
fen.input_7.clicked.connect(input7)
fen.input_8.clicked.connect(input8)
fen.input_9.clicked.connect(input9)